"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Userwrapper from "./userwrapper";
import { usePathname } from "next/navigation";
import Footer from "./_layout/footer";
import Navbar from "./_layout/navbar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const hideNavFooter = pathname === "/login" || pathname === "/signup";
  return (
    
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > {!hideNavFooter && <Navbar/>}
      <main>
     {children}
     <ToastContainer  position="top-right" autoClose={3000}></ToastContainer>
     </main>
       {!hideNavFooter && <Footer />}

       
      </body>
    </html>
  );
}

